import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/common/header/Header";
import ToasterProvider from "./providers/ToasterProvider";
import AccountModal from "./components/modal/AccountModal";
import getCurrentUser from "./actions/getCurrentUser";
import ClientOnly from "./components/ClientOnly";
import Footer from "./components/common/footer/Footer";
// import "@uploadthing/react/styles.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
export const dynamic = "force-dynamic";
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header currentUser={currentUser} />
        <ClientOnly>

        <AccountModal />
        <ToasterProvider />
   
        </ClientOnly>
      
        {children}
        <Footer/>
      </body>
    </html>
  );
}
